name: Fetch Secrets

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch secrets from Private Repo
        run: |
          pip install requests
          python scripts/fetch_secrets.py

      - name: Show secrets (optional)
        run: |
          ls secrets
